image:
  repository: bitnamilegacy/keycloak

auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: admin
  managementUser: manager
  managementPassword: manager
proxyAddressForwarding: true
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.kind.cluster
  tls: true
  extraTls:
    - hosts:
        - keycloak.kind.cluster
      secretName: keycloak.kind.cluster-tls

postgresql:
  image:
    repository: bitnamilegacy/postgresql
  enabled: true
  tls:
    enabled: false
  auth:
    postgresPassword: admin
